# Make sure to check the documentation at http://goreleaser.com

builds:
  - id: main
    dir: app
    binary: main
    main: main.go
    goos: [linux]
    goarch: [amd64]
    env: ["CGO_ENABLED=0"]

archives:
  - id: lambda
    rlcp: true
    format: zip
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - none*

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ .Tag }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

blobs:
  - provider: s3
    bucket: lambda-uploads-carrlos
    region: us-east-1
    folder: lambda-processor-app/artifacts/v{{ .Version }}

nightly:
  # Allows you to change the version of the generated nightly release.
  #
  # Note that some pipes require this to be semantic version compliant (nfpm,
  # for example).
  #
  # Default is `{{ incpatch .Version }}-{{ .ShortCommit }}-nightly`.
  # Templates: allowed
  name_template: '{{ incpatch .Version }}-devel'

  # Tag name to create if publish_release is enabled.
  tag_name: devel

  # Whether to publish a release or not.
  # Only works on GitHub.
  publish_release: true

  # Whether to delete previous pre-releases for the same `tag_name` when
  # releasing.
  # This allows you to keep a single pre-release.
  keep_single_release: true