apiVersion: awsblueprints.io/v1alpha1
kind: ServerlessApp
metadata:
  name: test-sqs-lambda-s3
  namespace: default
spec:
  compositionSelector:
    matchLabels:
      awsblueprints.io/provider: aws
      awsblueprints.io/environment: dev
      serverless.awsblueprints.io/app: sqs-lambda-s3
  bucketName: lambda-uploads-carrlos
  bucketKey: lambda-processor-app/artifacts/gitops-example-apps_0.1.0_linux_amd64.zip
  memorySize: 128
  resourceConfig:
    providerConfigName: aws-provider-config
    region: us-east-1
