apiVersion: awsblueprints.io/v1alpha1
kind: ServerlessApp
metadata:
  name: dev-sqs-lambda-s3
spec:
  imageName: lambda-processor:latest
  memorySize: 128
  resourceConfig:
    providerConfigName: aws-provider-config
    region: us-east-1
