apiVersion: awsblueprints.io/v1alpha1
kind: SubscriptionFilter
metadata:
  name: kinesis-firehose-s3-lambda
spec:
  forProvider:
    logGroupName: "/aws/eks/crossplane-blueprints/cluster"
    filterPattern: ""
    roleArnSelector:
      matchLabels:
        crossplane.io/claim-name: "kinesis-firehose-s3-lambda"
        crossplane.io/claim-namespace: default
        iam.awsblueprints.io/service: firehose
    destinationArn: "arn:aws:firehose:us-east-1:015299085168:deliverystream/dynatrace"
    # TODO there is an issue with destinationArnSelector not working for Kinesis Firehose https://github.com/upbound/upjet/issues/95
    #destinationArnSelector:
    #  matchLabels:
    #    crossplane.io/claim-name: kinesis-firehose-s3-lambda"
    #    crossplane.io/claim-namespace: default
    #    firehoseapps.awsblueprints.io/app: firehose
  resourceConfig:
    providerConfigName: aws-provider-config
    region: us-east-1


