apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dev-sqs-lambda-s3
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/csantanapr/gitops-example-apps.git
    targetRevision: HEAD
    path: claim/dev
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  syncPolicy:
    automated:
      prune: true
      allowEmpty: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true