name: Go releaser
on:
  push:
    branches:
      - main
    paths:
      - 'app/**'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
    - id: release
      uses: rymndhng/release-on-push-action@master
      with:
        bump_version_scheme: patch

    - name: checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - run: git fetch --force --tags

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - id: goreleaser
      uses: goreleaser/goreleaser-action@v4
      with:
        distribution: goreleaser
        version: latest
        args: release --clean
      env:
        REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        IMAGE_NAME: lambda-processor

    - uses: actions-ecosystem/action-get-latest-tag@v1
      id: get-latest-tag
      with:
        semver_only: true

    - name: Modify file
      run: |
        # Use sed to replace the bucketKey value in the file with the ARTIFACT_NAME
        sed -i "s/imageName:.*/imageName: lambda-processor:${{ steps.get-latest-tag.outputs.tag }}/g" claim/sqs-lambda-s3-claim.yaml

    - name: Commit & Push changes
      uses: actions-js/push@v1.4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        message: "Updating claim bucketKey version to ${{ env.ARTIFACT_NAME }}"
